FROM python:3.12-slim

WORKDIR /bot

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock ./

RUN poetry config virtualenvs.create false && poetry install --no-root

COPY . .

ENV PYTHONPATH=/bot/src

CMD ["poetry", "run", "python", "main.py"]