FROM python:3.12-slim

WORKDIR /api

RUN pip install poetry

COPY ./pyproject.toml ./poetry.lock ./

RUN poetry config virtualenvs.create false && poetry install --no-root

COPY . .

ENV PYTHONPATH=/api/src

EXPOSE 8000

CMD ["poetry", "run", "fastapi", "dev", "main.py"]